### Fetch all tasks
GET http://localhost:3200/tasks
Content-Type: application/json

### Create a task
POST http://localhost:3200/tasks
Content-Type: application/json

{
    "title": "Dummy Title 2nd",
    "date": "2023-02-21T12:00:00Z",
    "description": "lorem ipsium 2nd",
    "priority": "low",
    "status": "inProgress"
}

### Update a task
PUT http://localhost:3200/tasks
Content-Type: application/json

{
    "id": "0436bf84-a14b-4850-a6e0-fd48a09848a3",
    "status": "inProgress"
}